---
# tasks file for roles/nto.reports

- name: ensure reports dir is created
  file: >
    dest=/var/dbase/reports
    state=directory
    owner=root
    group=root
    mode=0755

- name: copy SQL files
  template: >
    dest=/usr/local/bin/{{ item }}
    src={{ item }}
    owner=root
    group=root
    mode=0755
  with_items:
  - tess_readings_daily_summary.sh
  - tess_bulk_dump_by_instrument.sh
  - tess_sunrise_sunset.sh

- name: install sunrise/sunset historic
  cron: >
    name="TESS sunrise/sunset times" 
    minute=0
    hour=13
    user="root" 
    job="/usr/local/bin/tess_sunrise_sunset.sh"
    cron_file=tess_sunrise_sunset


- name: install daily readings summary
  cron: >
    name="Daily readings summary" 
    minute=5
    hour=13
    user="root" 
    job="/usr/local/bin/tess_readings_daily_summary.sh  > /var/dbase/reports/tess_readings_daily_summary.txt"
    cron_file=tess_daily_readings_summary

# Creates a cron file under /etc/cron.d
- name: install bulk dump cron jobs
  cron: >
    name="bulk dump cron job for {{ item.name }}" 
    minute={{ item.minute }} 
    hour={{ item.hour }}
    user="root" 
    job="/usr/local/bin/tess_bulk_dump_by_instrument.sh {{ item.name }} | gzip > /var/dbase/reports/{{ item.name }}.csv.gz"
    cron_file=bulk_dump_by_instrument_{{ item.name }}
  with_items:
  - { name: stars1, hour: 13, minute: 15 }
  - { name: stars2, hour: 13, minute: 20 }
  - { name: stars4, hour: 13, minute: 22 }
  - { name: stars5, hour: 13, minute: 24 }
  - { name: STARS7, hour: 13, minute: 26 }
  - { name: stars8, hour: 13, minute: 28 }

