---
# tasks file for roles/nto.reports

- name: ensure reports dir is created
  file: >
    dest=/var/dbase/reports
    state=directory
    owner=root
    group=root
    mode=0755

- name: copy additional SQL report files
  template: >
    dest=/usr/local/bin/{{ item }}
    src={{ item }}
    owner=root
    group=root
    mode=0755
  with_items:
  - tess_catalog.sh
  - tess_changelog.sh

- name: install generic cron jobs
  cron: >
    name="cron job for {{ item.name }}" 
    minute={{ item.minute }}
    hour={{ item.hour }}
    user="root" 
    job="/usr/local/bin/{{ item.name }}.sh {{ item.dbase }}"
    cron_file={{ item.name }}
  with_items:
  - { name: tess_sunrise_sunset, hour: 9,  minute:  0, dbase: /var/dbase/tess.db }
  - { name: tess_catalog,        hour: 9,  minute:  5, dbase: /var/dbase/tess.db }
  - { name: tess_changelog,      hour: 9,  minute: 10, dbase: /var/dbase/tess.db }
  - { name: tess_daily_summary,  hour: 9,  minute: 15, dbase: /var/dbase/tess.db }
  - { name: tess_bulk_dump,      hour: 13, minute: 15, dbase: /var/dbase/tess.db-\* }
  - { name: tess_ida_bulk_dump,  hour: 12, minute: 45, dbase: /var/dbase/tess.db-\* }
 
