---
# tasks file for roles/nto.reports

- name: ensure reports dir is created
  file: >
    dest=/var/dbase/reports
    state=directory
    owner=root
    group=root
    mode=0755

- name: copy additional SQL report files
  template: >
    dest=/usr/local/bin/{{ item }}
    src={{ item }}
    owner=root
    group=root
    mode=0755
  with_items:
  - tess_catalog.sh
  - tess_changelog.sh

- name: install generic cron jobs
  cron: >
    name="cron job for {{ item.name }}" 
    minute={{ item.minute }}
    hour={{ item.hour }}
    user="root" 
    job="/usr/local/bin/{{ item.name }}.sh"
    cron_file={{ item.name }}
  with_items:
  - { name: tess_sunrise_sunset,    hour: 9, minute:  0 }
  - { name: tess_daily_summary,     hour: 9, minute: 10 }
  - { name: tess_catalog,           hour: 9, minute: 12 }
  - { name: tess_changelog,         hour: 9, minute: 12 }
  - { name: tess_instruments_file,  hour: 9, minute: 25 }
  - { name: tess_bulk_dump,         hour: 9, minute: 30 }
  - { name: tess_ida_bulk_dump,     hour: 9, minute: 45 }
 
