---
# This Playbook prepares a brand new Raspberry Pi 
# for an All-In-One-Wonder router, Webcam, & eather website
- hosts: consumers
  become: yes

  pre_tasks:

  # Only run "update_cache=yes" once a day
  - name: update apt cache once a day
    apt: update_cache=yes cache_valid_time=86400

  # Esto es en la Raspberry Pi de la UCM
  - name: mount /dev/sda1 partition onto database directory
    mount: >
      name={{ tessdb_dbase_dir }}
      src=/dev/sda1 
      fstype=ext4 
      opts=noatime 
      state=mounted
    when: ansible_hostname == "rb-tess"


  roles:
  
  # Execute this only on the Raspberry Pi
  - role: tersmitten.timezone 
    tags: [ common ]
    when: ansible_hostname == "rb-tess"

  - role: nto.logrotate      
    tags: [ common ] 

  - role: nto.tessdb          
    tags: [ tessdb ]

  - role: nto.monit          
    tags: [ monit ]

  - role: nto.reports          
    tags: [ reports ]
 
