---

# This Playbook prepares a brand new Raspberry Pi for its new purpose
# 1) Changes the hostname
# 2) Add a new user deleting the pi user or else keep the 'pi' user
# 3) Install SSH keys for the new user or the pi user
# ----------------------------------------------
# This is the second part of a two-stage process 
# that has several reboots in between
# ----------------------------------------------

- hosts: hardening2
  become: yes

  roles:

  # This role calls pi.hardening plus other roles
  - pi.basic
  
  post_tasks:

  - name: reboot the Raspberry Pi
    command: /sbin/reboot
    when: reboot_raspberry_pi is defined and reboot_raspberry_pi | bool

