---
# This Playbook prepares a brand new Raspberry Pi 
# for an All-In-One-Wonder router, Webcam, & eather website
- hosts: hotspot
  become: yes

  pre_tasks:

  # Only run "update_cache=yes" once a day
  - name: update apt cache once a day
    apt: update_cache=yes cache_valid_time=86400

  - name: allow packed forwarding inmediately
    command: echo 1 > /proc/sys/net/ipv4/ip_forward

  - name: allow packed forwarding after reboot
    lineinfile: >
      dest=/etc/sysctl.conf
      regexp="^#(net.ipv4.ip_forward=1)"
      line="\1"
      state=present
      backrefs=yes

  - name: configure iptables for routing packets
    command: '{{ item }}'
    with_items:
      - "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE"
      - "iptables -A FORWARD -i eth0  -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT"
      - "iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT"
      - "iptables-save > /etc/iptables.ipv4.nat"
    args:
      creates: /etc/iptables.ipv4.nat

  roles:
  
  - role: nto.network
    tags: [ network ]

  

# pi@raspberrypi:~ $ sudo iptables -t nat -S
# -P PREROUTING ACCEPT
# -P INPUT ACCEPT
# -P OUTPUT ACCEPT
# -P POSTROUTING ACCEPT
# pi@raspberrypi:~ $ sudo iptables -S
# -P INPUT ACCEPT
# -P FORWARD ACCEPT
# -P OUTPUT ACCEPT



# In /etc/network/interfaces añadir
#up iptables-restore < /etc/iptables.ipv4.nat