---
# This Playbook prepares a brand new Raspberry Pi 
- hosts: hotspot
  become: yes

  pre_tasks:

  - name: configure iptables for routing packets
    shell: >
      {{ item }}
    with_items:
      - iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      - iptables -A FORWARD -i eth0  -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
      - iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
      - iptables-save > /etc/iptables.ipv4.nat
    args:
      creates: /etc/iptables.ipv4.nat

  roles:

  - role: pi.facts
 
  - role: nto.network
    network_allow_forwarding: yes
    network_interfaces_delayed_restart: no
    tags: [ network ]

  # Avoid using wlan0 fro time requests
  - role: nto.ntp
    ntp_default_options: [ '-g', '-I eth0' ]
    tags: [ ntp ]

