---
# This Playbook prepares a brand new Raspberry Pi 
# for an All-In-One-Wonder router, Webcam, & eather website
- hosts: hotspot
  become: yes

  pre_tasks:

  # Only run "update_cache=yes" once a day
  - name: update apt cache once a day
    apt: update_cache=yes cache_valid_time=86400


  - name: configure iptables for routing packets
    shell: >
      {{ item }}
    with_items:
      - iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      - iptables -A FORWARD -i eth0  -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
      - iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
      - iptables-save > /etc/iptables.ipv4.nat
    args:
      creates: /etc/iptables.ipv4.nat

  roles:
  
  - role: nto.network
    network_allow_forwarding: yes
    network_interfaces_delayed_restart: no
    tags: [ network ]

