---

# ----------------
# Role: nto.reports
# -----------------

reports_list:
  - { name: stars1,  hour:  9, minute: 16 }
  - { name: stars2,  hour:  9, minute: 18 }
  - { name: stars3,  hour:  9, minute: 20 }
  - { name: stars4,  hour:  9, minute: 22 }
  - { name: stars5,  hour:  9, minute: 24 }
  - { name: stars6,  hour:  9, minute: 26 }
  - { name: stars7,  hour:  9, minute: 28 }
  - { name: stars8,  hour:  9, minute: 30 }
  - { name: stars9,  hour:  9, minute: 32 }
  - { name: stars10, hour:  9, minute: 34 }
  - { name: stars11, hour:  9, minute: 36 }
  - { name: stars12, hour:  9, minute: 38 }
  - { name: stars15, hour:  9, minute: 40 }
  - { name: stars16, hour:  9, minute: 42 }
  - { name: stars17, hour:  9, minute: 44 }
  - { name: stars18, hour:  9, minute: 46 }
  - { name: stars19, hour:  9, minute: 48 }
  - { name: stars21, hour:  9, minute: 50 }
  - { name: stars27, hour:  9, minute: 42 }
  - { name: stars30, hour:  9, minute: 54 }
  - { name: stars32, hour:  9, minute: 56 }
  - { name: stars55, hour:  9, minute: 58 }
  - { name: stars56, hour: 10, minute: 00 }
  - { name: stars59, hour: 10, minute: 02 }
  - { name: stars62, hour: 10, minute: 04 }
  - { name: stars63, hour: 10, minute: 06 }
  - { name: stars69, hour: 10, minute: 08 }
  - { name: stars70, hour: 10, minute: 10 }
  - { name: stars91, hour: 10, minute: 12 }